POST http://localhost:3333/login
Content-Type: application/json

{
  "username": "user2@user.com",
  "password": "123456"
}

###
GET http://localhost:3333/teste
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoidXNlcjJAdXNlci5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY3NTM1Mzk4MCwiZXhwIjoxNjc1MzU0MDQwfQ.P_eZczBPUcmW2yvF4mIk34Wht6k1MJvaP3CJRbrbIfc
